name: Setup Vapoursynth

description: Setup Vapoursynth in the current runner

inputs:
  vs-version:
    description: Vapoursynth version to use, defaults to latest
    required: true
    default: R65 # renovate: datasource=pypi dep_name=vapoursynth
  cython-version:
    description: Cython version to use, defaults to latest
    required: true
    default: 3.0.4 # renovate: datasource=pypi dep_name=cython

runs:
  using: composite
  steps:
    - name: Install vapoursynth deps
      if: runner.os == 'windows'
      shell: cmd
      run: |
        choco install zimg --confirm

    - name: Cache vapoursynth
      if: runner.os == 'linux' || runner.os == 'macos' || runner.os == 'windows'
      id: cache-vs
      uses: actions/cache@v3
      with:
        key: vs-${{ runner.os }}-${{ inputs.vs-version }}
        path: |
          /tmp/vapoursynth/*
          !/tmp/vapoursynth/.git
          !/tmp/vapoursynth/doc
          !/tmp/vapoursynth/installer
          !/tmp/vapoursynth/msvc_project

    - name: Set env vars
      if: runner.os == 'linux'
      shell: bash
      run: |
        echo "CORES=$(nproc)" >> $GITHUB_ENV
        echo "PREFIX=/usr" >> $GITHUB_ENV

    - name: Set env vars
      if: runner.os == 'macos'
      shell: bash
      run: |
        echo "CORES=$(sysctl -n hw.ncpu)" >> $GITHUB_ENV
        echo "PREFIX=/usr/local" >> $GITHUB_ENV

    - name: Set env vars
      if: runner.os == 'windows'
      shell: cmd
      run: |
        setx CORES "%NUMBER_OF_PROCESSORS%"
        setx PREFIX "C:\Program Files\VapourSynth"

    - name: Install vapoursynth make-deps
      if: (runner.os == 'linux' || runner.os == 'macos') && steps.cache-vs.outputs.cache-hit != 'true'
      shell: bash
      run: pip3 install "cython==${{ inputs.cython-version }}"

    - name: Install vapoursynth make-deps
      if: runner.os == 'windows' && steps.cache-vs.outputs.cache-hit != 'true'
      shell: cmd
      run: |
        pip install "cython==${{ inputs.cython-version }}"

    - name: Make vapoursynth
      if: (runner.os == 'linux' || runner.os == 'macos') && steps.cache-vs.outputs.cache-hit != 'true'
      shell: bash
      run: |
        git clone https://github.com/vapoursynth/vapoursynth /tmp/vapoursynth --depth 1 -b ${{ inputs.vs-version }}
        cd /tmp/vapoursynth
        ./autogen.sh
        ./configure --prefix=$PREFIX --disable-x86-asm --disable-vspipe
        make -j$CORES

    - name: Make vapoursynth
      if: runner.os == 'windows' && steps.cache-vs.outputs.cache-hit != 'true'
      shell: cmd
      run: |
        cd /tmp/vapoursynth
        msbuild.exe vapoursynth.sln /p:Configuration=Release /p:Platform=x64

    - name: Install vapoursynth
      if: runner.os == 'linux' || runner.os == 'macos'
      shell: bash
      run: |
        cd /tmp/vapoursynth
        sudo make install -j$CORES

    - name: Install vapoursynth
      if: runner.os == 'windows'
      shell: cmd
      run: |
        msiexec /i vapoursynth.msi

branding:
  icon: video
  color: gray-dark