name: windowstests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]

permissions:
  contents: read

jobs:
  tests:
    name: windowstests
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: ["3.8", "3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Clone Dependencies
        run: pip install git+https://github.com/vapoursynth/vsrepo.git

      - uses: actions/checkout@v4

      - name: Setup vapoursynth
        uses: ./

      - name: Install deps
        run: pip install -r requirements.txt

      - name: vsrepo install
        run: vsrepo.py install havsfunc ffms2 d2v

      - name: Check vsrepo
        run: vsrepo.py installed

      - name: Check vapoursynth
        run: python -c "import vapoursynth; print(vapoursynth.core.version_number())"