name: windowstests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]

permissions:
  contents: read

jobs:
  tests:
    name: windowstests
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, windows-2022, windows-2019]
        python-version: ["3.8", "3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/checkout@v4

      - name: Setup vapoursynth
        uses: ./

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Check vapoursynth
        run: python -c "import vapoursynth; print(vapoursynth.core.version_number())"