name: linuxtests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]

permissions:
  contents: read

jobs:
  tests:
    name: linuxtests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, macos-latest, macos-12, macos-11, macos-13]
        python-version: ["3.12", "3.13"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5

      - name: Setup vapoursynth
        uses: ./

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5

      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install deps
        run: uv pip install -r requirements.txt

      - name: Check vapoursynth
        run: | 
          uv run python -c "from vapoursynth import core; print(core)"
          uv run python -m unittest discover -s test -p "*test.py"